const mongoose = require("mongoose");

const carSchema = mongoose.Schema({
  id_trim: { type: String },
  make: { type: String },
  model: { type: String },
  generation: { type: String },
  year_from: { type: String },
  year_to: { type: String },
  series: { type: String },
  trim: { type: String },
  body_type: { type: String },
  number_of_seats: { type: String },
  length_mm: { type: String },
  width_mm: { type: String },
  height_mm: { type: String },
  wheelbase_mm: { type: String },
  front_track_mm: { type: String },
  rear_track_mm: { type: String },
  curb_weight_kg: { type: String },
  ground_clearance_mm: { type: String },
  max_trunk_capacity_l: { type: String },
  minimum_trunk_capacity_l: { type: String },
  maximum_torque_n_m: { type: String },
  injection_type: { type: String },
  cylinder_layout: { type: String },
  number_of_cylinders: { type: String },
  engine_type: { type: String },
  valves_per_cylinder: { type: String },
  cylinder_bore_mm: { type: String },
  stroke_cycle_mm: { type: String },
  turnover_of_maximum_torque_rpm: { type: String },
  capacity_cm3: { type: String },
  engine_hp: { type: String },
  engine_hp_rpm: { type: String },
  drive_wheels: { type: String },
  number_of_gears: { type: String },
  turning_circle_m: { type: String },
  transmission: { type: String },
  acceleration_0_100_km: { type: String },
  max_speed_km_per_h: { type: String },
  front_brakes: { type: String },
  fuel_grade: { type: String },
});

module.exports = mongoose.model("Car", carSchema);
